#!/bin/tcsh -f
set my_editor = "`printf "\""${0}"\"" | sed 's/.*\/\([^\.]\+\).*/\1/g'`"
switch ( "${my_editor}" )
case "connectED":
case "gedit":
	breaksw
case "vi":
case "vim":
case "vim-enhanced":
default:
	set my_editor = `printf "%s -p" "vim-enhanced"`
	breaksw
endsw

${my_editor} "./data/get2gnow.schemas.in" "./data/online-services-dialog.ui" "./src/debug.c" "./src/keyring.c" "./src/online-service.c" "./src/online-services.c" "./src/online-services-dialog.c"

