#!/bin/tcsh -f
set my_editor = "`printf "\""${0}"\"" | sed 's/.*\/\([^\:]\+\).*/\1/g'`"

if("${my_editor}" == "${0}" ) then
	echo "**error:** unable to determine session editor
your default editor will be used.";
	set my_editor="${EDITOR}";
endif

switch ( "${my_editor}" )
case "connectED":
case "gedit":
	breaksw
case "vi":
case "vim":
case "vim-enhanced":
default:
	set my_editor = `printf "%s -p" "vim-enhanced"`
	breaksw
endsw

${my_editor} ""/projects/gtk/get2gnow/data/main-window.in.ui ""/projects/gtk/get2gnow/src/hotkeys.c ""/projects/gtk/get2gnow/src/macros.h ""/projects/gtk/get2gnow/src/main-window.c ""/projects/gtk/get2gnow/src/Makefile.am ""/projects/gtk/get2gnow/src/Makefile.in ""/projects/gtk/get2gnow/src/online-service-request.c ""/projects/gtk/get2gnow/src/online-service-request.h ""/projects/gtk/get2gnow/src/online-service-request.types.h ""/projects/gtk/get2gnow/src/program.h ""/projects/gtk/get2gnow/src/uberchick-label.c ""/projects/gtk/get2gnow/src/update-viewer.c;

