.TH "deprecated" 3 "Wed Sep 1 2010" "Version 0.8.9" "OAuth library functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- .TH "deprecated" 3 "Wed Sep 1 2010" "Version 0.8.9" "OAuth library functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \-  
.IP "\fBGlobal \fBoauth_sign_array\fP(int *argcp, char ***argvp, char **postargs, OAuthMethod method, const char *c_key, const char *c_secret, const char *t_key, const char *t_secret) attribute_deprecated \fP" 1c
Use \fBoauth_sign_array2()\fP instead.
.PP
.PP
 
.IP "\fBGlobal \fBoauth_sign_url\fP(const char *url, char **postargs, OAuthMethod method, const char *c_key, const char *c_secret, const char *t_key, const char *t_secret) attribute_deprecated \fP" 1c
Use \fBoauth_sign_url2()\fP instead.
.PP

